### ISSUE TITLE
Drive Base [TRACKER]

### ISSUE THREAD

**Issue by Stellanora64** [Warwick1269/LTBT_FRC#2]
As we are using a mecanum drive base, there are many things that need to be re-written and changed. This issue is to track the various issues / things that need to be done. 

- [x] Assign motors to correct motor drivers.
- [x] Move current drive base code to its own library to be interfaced with.
- [x] Robot orientation drive
- [x] ~Cubic speed interpolation (may need testing to see if drivers prefer it over linear)~ There appears to be a built in function for this here: [https://docs.wpilib.org/en/stable/docs/software/hardware-apis/motors/wpi-drive-classes.html](https://docs.wpilib.org/en/stable/docs/software/hardware-apis/motors/wpi-drive-classes.html)
- [x] Input smoothing? ([slew rate limiter](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/filters/slew-rate-limiter.html#slew-rate-limiter))
- [ ] #3 
- [x] Joystick control (as in the logitech one)
- [x] Change deadzone code to setDeadband()
- [x] Change maxspeed code to setMaxOutput()
