### ISSUE TITLE
Arm/Intake [TRACKER]

### ISSUE THREAD

**Issue by Stellanora64** [Warwick1269/LTBT_FRC#4]
This issue is a tracker for all things arm related.

- [x] Assign motor drivers.
- [ ] Adjust speeds, so it doesn't destroy itself.
- [x] Add in motor safety to the arm  
- [x] Analogue control
- [ ] ~Cubic speed interoperation? (will need testing)~ Sign kept squaring (may leave as linear though)
- [x] [slew rate limiter](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/filters/slew-rate-limiter.html#slew-rate-limiter) on the arm's movement to help smooth it out. (Will need testing)
- [x] #5
